import Head from 'next/head';
import Board from '../components/Board/board';
import Suitable from '../components/Elements/Suitable/suitable';
import Messanger from '../components/Messanger/messanger';
import styles from '../styles/Home.module.scss';
import Selected from './../components/Selected/selected';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>AutoPass</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<Board />
			<Suitable />
			<Messanger />
			<Selected />
		</div>
	);
}
